/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Registers '@robby-rabbitman/nx-plus-web-dev-server/plugins/web-dev-server' in the 'nx.json'.
 */
export interface WebDevServerInitGeneratorOptions {
  /**
   * The name of the Web Dev Server serve target.
   */
  serveTargetName?: string;
  /**
   * Whether to skip formatting the updated files.
   */
  skipFormat?: boolean;
  /**
   * Whether to skip adding the plugin.
   */
  skipAddPlugin?: boolean;
  [k: string]: unknown;
}
