uplinks:
  npmjs:
    url: https://registry.npmjs.org/
    maxage: 60m

packages:
  '@robby-rabbitman/nx-plus-**':
    access: $all
    publish: $all
    unpublish: $all

  '**':
    access: $all
    publish: $all
    unpublish: $all
    proxy: npmjs

log:
  type: stdout
  format: pretty
  level: warn

publish:
  allow_offline: true
