/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Registers '@robby-rabbitman/nx-plus-web-test-runner/plugins/web-test-runner' in the 'nx.json'.
 */
export interface WebTestRunnerInitGeneratorOptions {
  /**
   * The name of the Web Test Runner test target.
   */
  testTargetName?: string;
  /**
   * Whether to skip formatting the updated files.
   */
  skipFormat?: boolean;
  /**
   * Whether to skip adding the plugin.
   */
  skipAddPlugin?: boolean;
  [k: string]: unknown;
}
