name: publish

on:
  workflow_dispatch:
    inputs:
      dry-run:
        type: boolean
        default: true
  release:
    types:
      - published

jobs:
  main:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    env:
      NX_PLUS_DEV_CONTAINER_EXEC_ARGS: --remote-env CI=true

    steps:
      - uses: actions/checkout@v4

      - run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'
          registry-url: 'https://registry.npmjs.org'

      - run: pnpm whoami && echo 'npm credentials are valid' || (echo 'npm credentials are invalid or have expired.' && exit 1)
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}

      - run: corepack enable

      - run: sh .devcontainer/exec-cmd.sh nx report

      # when it is not a tag (release) => dont publish
      - run: sh .devcontainer/exec-cmd.sh sh -c "NODE_AUTH_TOKEN=${{ secrets.NPM_ACCESS_TOKEN }} NPM_CONFIG_PROVENANCE=true nx run tools-nx-publish:publish-nx-plus-cli --dry-run=${{ github.ref_type != 'tag' || (github.event_name == 'workflow_dispatch' && inputs.dry-run) }} --verbose=${{ runner.debug && true || false }}"
