name: publish

on:
  workflow_dispatch:
    inputs:
      dry-run:
        type: boolean
        default: true
  release:
    types:
      - published

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      # remove global install of corepack or pin to a version
      - run: |
          npm i -g corepack
          corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
          registry-url: https://registry.npmjs.org

      - run: pnpm whoami || (echo 'npm credentials are invalid or have expired.' && exit 1)
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}

      - run: pnpm i

      - run: pnpm nx report

      - run: pnpm nx tools-release:exec-release-cli:ci --dry-run=${{ env.DRY_RUN }} --npm-registry=${{ env.NPM_REGISTRY }}
        env:
          # when it is not a tag (release) => dont publish
          DRY_RUN: ${{ github.ref_type != 'tag' || (github.event_name == 'workflow_dispatch' && inputs.dry-run) }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
          NPM_REGISTRY: https://registry.npmjs.org
          NX_VERBOSE_LOGGING: ${{ runner.debug && true || false }}
