name: release

on:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'

      - run: pnpm i

      - run: pnpm exec nx report

      - run: pnpm exec nx release --skip-publish
        env:
          GIT_AUTHOR_NAME: robby-rabbitman/nx-plus release
          GIT_AUTHOR_EMAIL: robby.rabbitman+nx-plus@gmail.com
