name: release

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: The version to use for the release.
        default: ''
      dry-run:
        type: boolean
        default: true
  push:
    branches:
      - 'main'

jobs:
  main:
    if: "${{ github.event_name == 'workflow_dispatch' || !startsWith(github.event.head_commit.message, 'chore: release') }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - uses: actions/create-github-app-token@v1
        id: create-release-app-token
        with:
          app-id: 939073
          private-key: ${{ secrets.RELEASE_APP_PRIVATE_KEY }}

      - run: |
          git config user.email "robby.rabbitman+nx-plus@gmail.com"
          git config user.name "release"

      - run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'

      - run: pnpm i

      - run: pnpm exec nx report

      - run: pnpm exec nx release --skip-publish --dry-run=${{ env.DRY_RUN }} ${{ env.VERSION }}
        env:
          GITHUB_TOKEN: ${{ steps.create-release-app-token.outputs.token }}
          DRY_RUN: ${{ github.event_name == 'workflow_dispatch' && inputs.dry-run }}
          VERSION: ${{ github.event_name == 'push' && '' || inputs.version }}
